name: Deploy to GAE/Go SE

on:
  push:
    branches:
      - master # runs on each push to master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

#      - name: Run codecov
#        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

      - name: Config app engine environment variables
        run: go run cmd/deploy/env.go ${{ secrets.GCP_PROJECT }} ${{ secrets.GH_SECRET_TOKEN }} ${{ secrets.GH_WEBHOOK_SECRET }}

      - name: Initialize Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: Installing add on for golang
        run: sudo apt-get install google-cloud-sdk-app-engine-go

      - name: Publish app to Google App Engine
        run: |
          gcloud app deploy app.yaml --project=${{ secrets.GCP_PROJECT }} -q

      - name: Slack Notification
          uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: 'Deploy'
          mention: 'here'
          mention_if: 'failure'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
